name: Test x64_vm build and AMI creation

env:
  AWS_DEFAULT_OUTPUT: json
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET_NAME: ucentral-ap-firmware
  AWS_ACCOUNT_ID: ${{ secrets.UCENTRAL_S3_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.UCENTRAL_S3_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.UCENTRAL_S3_ACCESS_KEY_SECRET }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      x64_vm_image_name: ${{ steps.package_and_upload_image.outputs.x64_vm_image_name }}
    strategy:
      fail-fast: false
      matrix:
        target: ['x64_vm']

    steps:
    - uses: actions/checkout@v2

    - name: Build image for ${{ matrix.target }}
      id: build
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        make -j TARGET=${{ matrix.target }}

    - name: Package and upload image for ${{ matrix.target }}
      id: package_and_upload_image
      env:
        GH_BUILD_USERNAME: ${{ secrets.GH_BUILD_USERNAME }}
        GH_BUILD_PASSWORD: ${{ secrets.GH_BUILD_PASSWORD }}
        ARTIFACTORY_USERNAME: cicd-indoor-main
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |
        LOWERCASE_TARGET=`echo ${{ matrix.target }} | tr '[:upper:]' '[:lower:]'`
        HASH=$(git rev-parse --short HEAD)

        if [[ ${GITHUB_REF} == "refs/heads/"* ]]
        then
          REF=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          IS_RELEASE="false"
        else
          REF=$(echo ${GITHUB_REF#refs/tags/} | tr '/' '-')
          IS_RELEASE="true"
        fi

        BASENAME="$(date +%Y%m%d)-$LOWERCASE_TARGET-$REF-$HASH"
        TAR_NAME="$BASENAME.tar.gz"
        IMG_NAME="$BASENAME-upgrade.bin";
        JSON_NAME="$BASENAME.json";

        tar cfz "$TAR_NAME" -C openwrt/bin/targets/ .
        curl -s -u $GH_BUILD_USERNAME:$GH_BUILD_PASSWORD -T "$TAR_NAME" "https://tip.jfrog.io/artifactory/tip-wlan-ap-firmware/uCentral/$LOWERCASE_TARGET/"$TAR_NAME""
        IMG_NAME="$BASENAME-upgrade.bin";
        TIP_VERSION="$(grep DISTRIB_TIP= openwrt/tmp/openwrt_release | cut -d\' -f2)"
        echo -e "{\n\t\"image\":\""${IMG_NAME}"\",\n\t\"revision\": \""${TIP_VERSION}"\",\n\t\"timestamp\":\""$(date +%s)"\",\n\t\"compatible\": \""${LOWERCASE_TARGET}"\"\n}" > latest-upgrade.json
        [ -f openwrt/tmp/image-file ] && curl -s -u $GH_BUILD_USERNAME:$GH_BUILD_PASSWORD -T "openwrt/$(cat openwrt/tmp/image-file)" "https://tip.jfrog.io/artifactory/tip-wlan-ap-firmware/uCentral/$LOWERCASE_TARGET/"$IMG_NAME""
        [ -f openwrt/tmp/image-file ] && curl -s -u $GH_BUILD_USERNAME:$GH_BUILD_PASSWORD -T "latest-upgrade.json" "https://tip.jfrog.io/artifactory/tip-wlan-ap-firmware/uCentral/$LOWERCASE_TARGET/latest-upgrade.json"

        [ -f openwrt/tmp/image-file ] && aws s3 cp --acl public-read --content-type "application/octet-stream" "openwrt/$(cat openwrt/tmp/image-file)" "s3://$AWS_S3_BUCKET_NAME/$IMG_NAME"
        [ -f openwrt/tmp/image-file ] && aws s3api put-object-tagging --bucket "$AWS_S3_BUCKET_NAME" --key "$IMG_NAME" --tagging "{\"TagSet\":[{\"Key\":\"release\",\"Value\":\"$IS_RELEASE\"}]}"
        [ -f openwrt/tmp/image-file ] && aws s3 cp --acl public-read --content-type "application/json" "latest-upgrade.json" "s3://$AWS_S3_BUCKET_NAME/$JSON_NAME"
        [ -f openwrt/tmp/image-file ] && aws s3api put-object-tagging --bucket "$AWS_S3_BUCKET_NAME" --key "$JSON_NAME" --tagging "{\"TagSet\":[{\"Key\":\"release\",\"Value\":\"$IS_RELEASE\"}]}"

        if [[ ${{ matrix.target }} == 'x64_vm' ]]; then
          echo ::set-output name=x64_vm_image_name::"$(echo $IMG_NAME)"
        fi

  create-x64_vm-ami:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        ref: WIFI-7206-add-workflow-to-build-virtual-ap-image

    - name: Use create-ami-from-image composite action
      uses: ./.github/actions/create-ami-from-image
      with:
        firmware_image_name: ${{ needs.build.outputs.x64_vm_image_name }}
        firmware_image_s3_bucket: ${{ env.AWS_S3_BUCKET_NAME }}
